apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ch2owbbpz-go 
  janus-idp.io/tekton: ch2owbbpz-go
  backstage.io/kubernetes-id: ch2owbbpz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ch2owbbpz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  