apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ch2owbbpz-go-gitops
  description: This is GitOps manifest for ch2owbbpz-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ch2owbbpz-go
    backstage.io/kubernetes-id: ch2owbbpz-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ch2owbbpz-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ch2owbbpz-go
