apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ch2owbbpz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ch2owbbpz-go 
  name: ch2owbbpz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ch2owbbpz-go 
